### ISSUE TITLE
ctrl+left and ctrl+right has been changed/broke in Less >= 3.0.0

### ISSUE THREAD

**Issue by hawkerboy7** [SublimeText/Less#1]
Hi deathaxe/braver,

Switching to less >= 3.0.0 the behaviour of ctrl+left and ctrl+right has been changed and now seems to regard the middle dash "-" the same as underscore "_".
Can this be reverted / fixed? :)

## Example
If you name a class `.test--test {}`.
The cursor used to move from here:
`.test--test| {}`
to here
`.test--|test {}`
when pressing ctrl+left.

In less 3.0.0 and 3.0.1 it goes here:
`.|test--test {}`

Works Less 2.7.5
Works Less 2.7.6
Broke/Changed? Less 3.0.0
Broke/Changed? Less 3.0.1

**Comment by hawkerboy7** [comment]
I also checked other text highlighting:
- ActionScript
- AppleScript
- ASP
- HTML
- JS
- JSON
- Plain Text
But this behavior only happens in Less >= 3.0.0.

I looked at the differences between 2.7.6 and 3.0.1 but I am not sure where to look so could not pinpoint it.

**Comment by hawkerboy7** [comment]
Maybe a helpfull pointer:

I checked the CSS highlighting and it behaves the same way (on a clean install of ST4).
> Less extends Sublime Text's CSS syntax definition as of ST4149.

Assuming Less < 3.0.0 does not extend Sublime Text's CSS or a lower version, the behaviour then probably comes from Sublime Text's CSS and not Less.

**Comment by deathaxe** [comment]
Dashes are part of identifiers in CSS and thus were removed from `word_separators`.

see: https://github.com/sublimehq/Packages/issues/2709

The same has been applied to Less for it to behave consistently and to be able to quickly navigate between begin/end of whole identifiers and sub-words.

Subword navigation works via <kbd>alt+left</kbd> and <kbd>alt+right</kbd>.

The behaviour can be modified by adjusting `word_separators` and `sub_word_separators` in syntax-specific settings. The defaults are https://github.com/SublimeText/Less/blob/master/Syntaxes/Less.sublime-settings

**Comment by hawkerboy7** [comment]
Your answer is clear, thank you for your time!
